name: Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Get dependencies and build
      run: |
        yarn install
        yarn build

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.7.2
      with:
        branch: dist
        folder: dist
    
    - name: Update submodule
      env:
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global credential.helper store
        git clone --recurse-submodules https://$GIT_USER:$GIT_TOKEN@github.com/moetools/www.git www
        cd www
        git submodule update --remote
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "feat: update submodule sub-web"
        git push